apiVersion: v1
kind: Service
metadata:
  name: psytest-back
  namespace: psytest
spec:
  type: ClusterIP
  clusterIP: 10.96.80.80
  selector:
    app: java-back
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: live-port
    #nodePort: 30080
