apiVersion: apps/v1
kind: Deployment
metadata:
  name: psytest-front
  namespace: psytest
  labels:
    app: front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-front
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: java-front
        label: v1
    spec:
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: harborpass
      containers:
      - name: front-nginx
        image: 192.168.77.20/psytest/front:1.0
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - "bin/sh"
              - "-c"
              - "sleep 3"
        resources:
          requests:
            memory: "150Mi"
          limits:
            memory: "500Mi"
        ports:
        - name: front-port
          containerPort: 80
          hostPort: 80
       #readinessProbe:
       #   tcpSocket:
       #     port: 80
       #   initialDelaySeconds: 5
       #   periodSeconds: 5
       #   failureThreshold: 3
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 300
          failureThreshold: 3
        volumeMounts:
        - name: default-conf
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 900
      volumes:
      - name: default-conf
        configMap:
          name: nginx-conf
